name: Deploy to AWS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: prod

    permissions:
      id-token: write
      contents: read

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: '20'

      - run: npm ci

      - run: npm install -g serverless

      - name: Configure AWS credentials from OIDC
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::771362849871:role/github-oidc-lambda-deployer
          aws-region: us-east-1

      - run: serverless deploy
        env:
          SMTP_USERNAME: ${{ vars.SMTP_USERNAME }}
          SMTP_FROM_EMAIL: ${{ vars.SMTP_FROM_EMAIL }}
          SMTP_TO_EMAIL: ${{ vars.SMTP_TO_EMAIL }}
          SERVERLESS_ACCESS_KEY: ${{ secrets.SERVERLESS_ACCESS_KEY }}
